import { levels } from '../content/levels';
import { registry } from '../core/machines';
import { formatValue } from '../core/values';
import type { GameState } from '../state/game-state';
import { colorHex, escape } from './helpers';
export function palette(state: GameState): string {
  const captions: Record<string, string> = { source: 'Входные данные', output: 'Результат', arithmetic: 'Арифметика', comparator: 'Сравнение', constant: 'Значение', split: 'Разделить поток', join: 'Собрать поток', stack: 'Последний → первый', queue: 'Первый → первый', branch: 'Условная развилка', filter: 'Отбор элементов', memory: 'Переменная' };
  return '<div class="palette-section">БЛОКИ ВЫЧИСЛЕНИЙ</div>' + state.level.availableMachines.map(type => {
    const d = registry.get(type); return `<button class="machine-card" data-machine="${type}" draggable="${state.mode === 'EDIT'}" title="${escape(d.description)}"><span class="machine-icon" style="--machine-color:${colorHex(d.color)}">${d.icon}</span><span><strong>${d.name}</strong><small>${escape(captions[type])}</small></span><i>⠿</i></button>`;
  }).join('') + '<div class="unlock-note"><span>◇</span> Новые машины открываются<br>в следующих заданиях.</div><button class="text-button" data-action="hint">Нужна подсказка? ↗</button>';
}
export function inspector(s: GameState): string {
  const m = s.graph.machines.find(m => m.id === s.selected);
  if (!m) {
    if (s.selectedConnection) return `<div class="inspector-body"><div class="large-symbol">→</div><h3>Соединение</h3><p>Пакеты идут по стрелке от выхода к входу.</p><button class="danger" data-action="remove" ${s.mode === 'RUN' ? 'disabled' : ''}>Удалить связь</button></div>`;
    return `<div class="mission-card"><small>ВАША ЗАДАЧА</small><h3>${escape(s.level.name)}</h3><p>${escape(s.level.description)}</p><div class="mission-example"><small>ВХОД → РЕЗУЛЬТАТ</small><code>${escape(formatValue(s.level.tests[0].input))} <span>→</span> ${escape(formatValue(s.level.tests[0].expected))}</code></div><button class="text-button" data-action="hint">Показать подсказку ↗</button></div><div class="inspector-placeholder"><span>⌖</span><h3>Взгляд изнутри</h3><p>Выберите машину на поле,<br>чтобы настроить её и увидеть<br>состояние данных.</p></div><div class="inspector-note"><span>i</span> В режиме RUN инспектор показывает реальные входы и выходы машины.</div>`;
  }
  const d = registry.get(m.type), snap = s.simulation?.snapshots.get(m.id), locked = s.mode === 'RUN';
  return `<div class="inspector-body"><div class="selected-machine"><span class="machine-icon" style="--machine-color:${colorHex(d.color)}">${d.icon}</span><div><h3>${d.name}</h3><small>${m.id} · ${snap?.status ?? 'edit'}</small></div></div><p>${escape(d.description)}</p>
    ${d.fields.map(f => `<label class="config-field">${escape(f.label)}${f.kind === 'select' ? `<select data-config="${f.key}" ${locked ? 'disabled' : ''}>${f.options!.map(o => `<option value="${escape(o)}" ${m.config[f.key] === o ? 'selected' : ''}>${escape(o)}</option>`).join('')}</select>` : `<input data-config="${f.key}" data-kind="value" value="${escape(formatValue(m.config[f.key]))}" ${locked ? 'disabled' : ''}/>`}</label>`).join('')}
    <h4>ВХОДЫ</h4>${d.ports.filter(p => p.direction === 'input').map(p => `<div class="port-row"><span>● ${p.label} <small>${p.types.join('/')}${p.required ? '' : ' · optional'}</small></span><code>${snap ? escape(JSON.stringify(snap.inputs[p.id] ?? [])) : '—'}</code></div>`).join('') || '<p class="muted">Вход уровня</p>'}
    <h4>ВЫХОДЫ</h4>${Object.entries(snap?.outputs ?? {}).map(([p, values]) => `<div class="port-row"><span>${escape(p)}</span><code>${escape(JSON.stringify(values))}</code></div>`).join('') || '<p class="muted">Ожидание вычисления…</p>'}
    ${snap && Object.keys(snap.state).length ? `<h4>ВНУТРЕННЕЕ СОСТОЯНИЕ</h4>${Object.entries(snap.state).map(([key, value]) => `<div class="port-row"><span>${escape(key)}</span><code>${escape(formatValue(value))}</code></div>`).join('')}` : ''}
    <button class="danger delete-machine" data-action="remove" ${locked ? 'disabled' : ''}>Удалить машину <kbd>Del</kbd></button></div>`;
}
export function testsPanel(s: GameState): string {
  const visible = s.level.tests.filter(t => !t.hidden), hidden = s.level.tests.filter(t => t.hidden).length;
  return `<div class="tests-layout"><div class="test-table"><div class="test-row table-head"><span>ПРОВЕРКА</span><span>ВХОД</span><span>ОЖИДАЕМ</span><span>ПОЛУЧЕНО</span><span>СТАТУС</span></div>${visible.map((t, i) => {
    const result = s.result?.tests[i]; return `<div class="test-row"><span class="muted">${String(i + 1).padStart(2, '0')}</span><code>${escape(formatValue(t.input))}</code><code>${escape(formatValue(t.expected))}</code><code title="${escape(result?.error ?? '')}">${result ? result.error ? 'Ошибка' : escape(JSON.stringify(result.actual.length === 1 ? result.actual[0] : result.actual)) : '—'}</code><span class="${result ? result.passed ? 'pass' : 'fail' : 'muted'}">${result ? result.passed ? '✓ Пройден' : '× Ошибка' : '○ Ожидание'}</span></div>`;
  }).join('')}<div class="hidden-tests">◇ ${hidden} скрытых теста проверяют универсальность решения <span>${s.result ? `${s.result.tests.filter(t => t.hidden && t.passed).length}/${hidden}` : '•••'}</span></div></div><div class="test-summary">${s.result ? `<span class="summary-label ${s.result.passed ? 'mint' : ''}">${s.result.passed ? '✓ ФАБРИКА РАБОТАЕТ' : '↳ ПРОВЕРЬТЕ РЕШЕНИЕ'}</span><strong>${s.result.tests.filter(t => t.passed).length}<small> / ${s.result.tests.length} тестов</small></strong><p>${s.result.machines} машин · ${s.result.connections} связей<br>${s.result.operations} операций · ${s.result.ticks} тиков</p>${s.result.passed ? `<div class="medals">${s.result.machines <= s.level.medals.machines ? '<span>◇ Compactness</span>' : ''}${s.result.operations <= s.level.medals.operations ? '<span>◇ Efficiency</span>' : ''}${s.result.ticks <= s.level.medals.ticks ? '<span>◇ Throughput</span>' : ''}</div><button class="primary next-button" data-action="next">${levels.indexOf(s.level) === 9 ? 'Карта уровней' : 'Следующий уровень'} →</button>` : `<p class="error-detail">${escape(s.result.tests.find(t => t.error)?.error ?? 'Результат отличается от ожидаемого. Проверьте входы машин.')}</p>`}` : `<span class="summary-label">ТЕСТОВЫЙ СИГНАЛ</span><label for="sample">Вход для анимации</label><select id="sample" ${s.mode === 'RUN' ? 'disabled' : ''}>${visible.map((t, i) => `<option value="${i}" ${i === s.sample ? 'selected' : ''}>${escape(formatValue(t.input))}</option>`).join('')}</select><p>RUN показывает один пример.<br>Затем проверяет все тесты.</p>`}</div></div>`;
}
export function mapPanel(s: GameState): string {
  const progress = s.persistence.progress();
  return `<p class="map-intro">От первого сигнала до собственного алгоритма. Все задания доступны для экспериментов.</p><div class="level-map">${levels.map((l, i) => `<button class="level-card ${progress[l.id] ? 'completed' : ''} ${s.level.id === l.id ? 'current' : ''}" data-level="${l.id}"><span>${String(i + 1).padStart(2, '0')} <i>${progress[l.id] ? '✓' : '↗'}</i></span><small>${escape(l.topic.split(' / ')[1])}</small><strong>${escape(l.name)}</strong><p>${progress[l.id] ? `Рекорд: ${progress[l.id].machines} машин<br>${progress[l.id].operations} операций · ${progress[l.id].ticks} тиков` : `${l.availableMachines.length} типов машин · ${l.tests.length} тестов`}</p></button>`).join('')}</div>`;
}
