export const template = `
<header class="topbar"><a class="brand" href="#" aria-label="Data Factory"><span class="brand-icon">▥</span><span>DATA<span class="brand-light">FACTORY</span><small>ВЫЧИСЛЕНИЯ В ДВИЖЕНИИ</small></span></a><div class="top-divider"></div><span class="workspace-label">Лаборатория алгоритмов <span class="tag">BETA 1.0</span></span><div class="top-actions"><span id="progress-label"></span><button data-action="map" class="map-button">▦ <span>Карта уровней</span></button><button data-action="help" class="icon-button" title="Управление и подсказки">?</button><button data-action="settings" class="icon-button" title="Настройки">⚙</button></div></header>
<section class="levelbar"><div class="level-heading"><span id="level-number" class="level-number"></span><div><small id="level-topic"></small><h1 id="level-name"></h1></div></div><div class="execution-controls"><span id="mode" class="mode-pill">● EDIT</span><button data-action="edit" id="edit-btn" title="Остановить и вернуться к редактированию">↺ <span>В редактор</span></button><button data-action="step" id="step-btn" title="Одно логическое действие">▹| <span>Шаг</span></button><select id="speed" aria-label="Скорость симуляции"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option><option value="0">Instant</option></select><button data-action="run" id="run-btn" class="primary">▶ RUN</button></div></section>
<main class="workspace"><aside class="palette"><div class="panel-heading"><h2>Машины</h2><span id="machine-count" class="muted"></span></div><p class="panel-caption">Перетащите на рабочее поле</p><div id="palette-list"></div><div class="palette-footer"><span class="status-dot"></span> Система готова к сборке<small>Каждая машина — одна операция.</small></div></aside>
<section class="workbench"><div class="canvas-toolbar"><div class="toolbar-label"><span class="status-dot"></span> FACTORY FLOOR <span id="graph-count"></span></div><div><button data-action="undo" id="undo-btn" title="Отменить (Ctrl+Z)">↶</button><button data-action="redo" id="redo-btn" title="Повторить (Ctrl+Shift+Z)">↷</button><span class="toolbar-separator"></span><button data-action="export" title="Экспорт JSON">⇩</button><button data-action="import" title="Импорт JSON">⇧</button><button data-action="clear" title="Очистить поле (можно отменить)">⌫</button></div></div><div id="game" aria-label="Поле фабрики"></div>
<div id="empty-state"><div class="empty-eyebrow">ВАШ ПЕРВЫЙ АЛГОРИТМ</div><div class="ghost-flow"><span>↗<small>SOURCE</small></span><i>··········→</i><span>◎<small>OUTPUT</small></span></div><h2>Большие идеи начинаются<br>с одного соединения.</h2><p>Перетащите машину слева.<br>Постройте путь, по которому пойдут данные.</p><span class="empty-shortcut">DRAG · CONNECT · RUN</span></div>
<div id="tutorial" class="tutorial"></div><div class="canvas-bottom"><span>Панорама: пробел + мышь · Масштаб: колесо</span><div><button data-action="zoom-out" title="Уменьшить">−</button><button data-action="fit" title="Показать всю фабрику (F)">Вписать</button><button data-action="zoom-in" title="Увеличить">+</button></div></div></section>
<aside class="inspector"><div class="panel-heading"><h2>Инспектор</h2><span class="tiny-tag">LIVE</span></div><div id="inspector-content"></div></aside></main>
<section class="bottom-panel"><nav class="tabs"><button data-tab="tests" class="active">✓ Тесты <span id="test-count"></span></button><button data-tab="console">≡ Консоль</button><button data-tab="code">⌘ Code View</button><div class="tab-actions"><span id="stats-line"></span><button data-action="check" id="check-btn">Проверить все →</button></div></nav><div id="tab-content"></div></section>
<footer class="statusbar"><span id="status-message" role="status" aria-live="polite"></span><span id="save-status">LOCAL AUTOSAVE <i class="status-dot"></i></span></footer>
<dialog id="modal"><div class="modal-top"><h2 id="modal-title"></h2><button data-action="close-modal" class="icon-button" aria-label="Закрыть">×</button></div><div id="modal-content"></div></dialog><input type="file" id="import-file" accept="application/json,.json" hidden />`;
