import type { DataValue, Level, LevelTest } from '../../core/types';
const cases = (values: [DataValue, DataValue][]): LevelTest[] => values.map(([input, expected], i) => ({ input, expected, hidden: i >= 3 }));
const base = ['source', 'output'];
export const levels: Level[] = [
  { id: 'first-signal', name: 'Первый сигнал', topic: '01 / ОСНОВЫ ПОТОКА', description: 'Каждая программа начинается с данных. Постройте самую маленькую фабрику: передайте входное значение в Output без изменений.', hint: 'Добавьте Source и Output. Потяните от зелёного порта справа к порту слева.', inputType: 'number', availableMachines: base, tests: cases([[42, 42], [7, 7], [-3, -3], [0, 0], [128, 128]]), medals: { machines: 2, operations: 10, ticks: 25 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Потяните от правого порта SOURCE к левому порту OUTPUT. Можно нажать на порты по очереди.', condition: 'connection' },
    { text: 'Нажмите RUN, проследите за пакетом и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'double', name: 'Удвоение', topic: '02 / АРИФМЕТИКА', description: 'Умножьте каждое входное число на 2. Подключите число и константу к двум входам Math.', hint: 'Source → Math A; Constant(2) → Math B. У Math выберите *.', inputType: 'number', availableMachines: [...base, 'constant', 'arithmetic'], tests: cases([[5, 10], [12, 24], [-3, -6], [0, 0], [1.5, 3]]), medals: { machines: 4, operations: 20, ticks: 70 } },
  { id: 'plus-ten', name: 'Запас мощности', topic: '03 / КОНСТАНТЫ', description: 'Прибавьте 10 к входному числу. Измените параметры машин в инспекторе справа.', hint: 'У Constant значение 10, у Math операция +.', inputType: 'number', availableMachines: [...base, 'constant', 'arithmetic'], tests: cases([[5, 15], [12, 22], [-3, 7], [-10, 0], [0, 10]]), medals: { machines: 4, operations: 20, ticks: 70 } },
  { id: 'greater-ten', name: 'Порог допуска', topic: '04 / СРАВНЕНИЯ', description: 'Верните true, если входное число строго больше 10, иначе false. Равенство порогу не считается.', hint: 'Source → Compare A; Constant(10) → Compare B. Операция >.', inputType: 'number', availableMachines: [...base, 'constant', 'comparator'], tests: cases([[20, true], [5, false], [10, false], [-2, false], [10.1, true]]), medals: { machines: 4, operations: 20, ticks: 70 } },
  { id: 'even', name: 'Чёткий ритм', topic: '05 / КОМПОЗИЦИЯ', description: 'Определите, чётное ли число. Остаток от деления чётного числа на 2 равен нулю.', hint: 'Сначала Math с % и Constant(2), затем Compare с == и Constant(0).', inputType: 'number', availableMachines: [...base, 'constant', 'arithmetic', 'comparator'], tests: cases([[8, true], [7, false], [0, true], [-4, true], [-3, false], [101, false]]), medals: { machines: 6, operations: 36, ticks: 130 } },
  { id: 'reassemble', name: 'По частям', topic: '06 / ПОТОКИ', description: 'Разберите строку на символы и соберите её обратно. Проследите за отдельными пакетами между Split и Join.', hint: 'Source → Split → Join (string) → Output. Join ждёт конца потока.', inputType: 'string', availableMachines: [...base, 'split', 'join', 'queue'], tests: cases([['CAT', 'CAT'], ['DATA', 'DATA'], ['A B', 'A B'], ['', ''], ['🚀Я', '🚀Я']]), medals: { machines: 4, operations: 20, ticks: 115 } },
  { id: 'reverse-string', name: 'Обратный поток', topic: '07 / СТЕК', description: 'Разверните строку. Stack выдаёт элементы в обратном порядке: последний вошёл — первый вышел.', hint: 'Source → Split → Stack → Join → Output. Для пустой строки результат тоже пустая строка.', inputType: 'string', availableMachines: [...base, 'split', 'stack', 'queue', 'join'], tests: cases([['HELLO', 'OLLEH'], ['CAT', 'TAC'], ['PROGRAM', 'MARGORP'], ['', ''], ['A', 'A'], ['🚀Я', 'Я🚀']]), medals: { machines: 5, operations: 30, ticks: 240 } },
  { id: 'positive', name: 'Развилка', topic: '08 / УСЛОВИЯ', description: 'Для числа больше нуля верните "POSITIVE", для остальных — "NEGATIVE". Направьте данные по правильной ветке.', hint: 'Сравните Source с 0. Source также идёт в Branch data, Compare — в condition. Выходы Branch подключите к trigger двух Constant со строками; обе константы — в Output. Ноль → "NEGATIVE".', inputType: 'number', availableMachines: [...base, 'constant', 'comparator', 'branch', 'memory'], tests: cases([[5, 'POSITIVE'], [-2, 'NEGATIVE'], [0, 'NEGATIVE'], [0.1, 'POSITIVE'], [-100, 'NEGATIVE']]), medals: { machines: 7, operations: 35, ticks: 155 } },
  { id: 'filter', name: 'Контроль качества', topic: '09 / ФИЛЬТРАЦИЯ', description: 'Оставьте в массиве только числа строго больше 10. Порядок подходящих элементов должен сохраниться.', hint: 'Split → Compare A и Filter data. Constant(10) → Compare B; Compare(>) → Filter condition. Filter → Join в режиме array → Output.', inputType: 'array', availableMachines: [...base, 'split', 'constant', 'comparator', 'filter', 'join', 'queue'], tests: cases([[[2, 15, 5, 30], [15, 30]], [[10, 11, 12], [11, 12]], [[-2, 0, 8], []], [[], []], [[20, 20, -1, 100], [20, 20, 100]]]), medals: { machines: 7, operations: 35, ticks: 250 } },
  { id: 'palindrome', name: 'Зеркальная линия', topic: '10 / АЛГОРИТМЫ', description: 'Проверьте, читается ли строка одинаково в обе стороны. Сравните исходное значение с развёрнутым.', hint: 'Сделайте фабрику разворота. Исходный Source подключите ещё и к Compare A, результат Join — в B. Выберите ==. Пустая строка считается палиндромом.', inputType: 'string', availableMachines: [...base, 'split', 'stack', 'queue', 'join', 'comparator', 'memory'], tests: cases([['LEVEL', true], ['RADAR', true], ['HELLO', false], ['', true], ['A', true], ['AB', false], ['АБА', true]]), medals: { machines: 6, operations: 42, ticks: 360 } },
];
